version: '2'

services:
  server:
    build: 
      context: ../
      dockerfile: ./deploy/server.docker
    restart: always
    environment:
      DB_NAME: exp
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: db
      APP_PORT: 5000
      APP_HOST: "0.0.0.0"
    links: 
      - db
    expose:
      - 5000
  client:
    build: 
      context: ../
      dockerfile: ./deploy/client.docker
    environment:
      DOMAIN: examist.dev
    links:
      - server
    ports:
      - "80:80"
  db:
    build: 
      context: ../
      dockerfile: ./deploy/db.docker
      args:
        dump: exp-12042016-0217.sql
    expose:
      - 5432